# Generated by Django 3.0.7 on 2020-06-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200614_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionchoice',
            name='correct_answer',
            field=models.BooleanField(default=False),
        ),
    ]
