# Generated by Django 3.0.7 on 2020-06-14 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_instructorrole_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='parent_course_id',
            new_name='parent_course',
        ),
        migrations.RenameField(
            model_name='instructorrole',
            old_name='course_id',
            new_name='associated_course',
        ),
        migrations.RenameField(
            model_name='instructorrole',
            old_name='user_id',
            new_name='associated_user',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='parent_challenge_id',
            new_name='parent_challenge',
        ),
        migrations.RenameField(
            model_name='questionchoice',
            old_name='parent_question_id',
            new_name='parent_question',
        ),
    ]
