# Generated by Django 3.0.7 on 2020-06-19 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='parent_course',
        ),
        migrations.AddField(
            model_name='challenge',
            name='parent_skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Skill'),
            preserve_default=False,
        ),
    ]
