# Generated by Django 3.0.7 on 2020-06-25 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200625_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorrole',
            name='associated_user',
        ),
    ]
