# Generated by Django 3.0.7 on 2020-06-25 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_remove_instructorrole_associated_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorrole',
            name='associated_user',
            field=models.ForeignKey(default='7', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
