# Generated by Django 3.0.7 on 2020-07-01 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_instructorrole_associated_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='parent_skill',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.Skill'),
        ),
    ]
