# Generated by Django 3.0.7 on 2020-07-19 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200719_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='parent_course',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='parent_skill',
        ),
        migrations.AlterField(
            model_name='instructorrole',
            name='associated_challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Challenge'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
