# Generated by Django 3.0.7 on 2020-07-30 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_auto_20200719_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='password',
            field=models.CharField(default='0000', max_length=255),
        ),
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('associated_challenge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Challenge')),
                ('associated_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated_challenge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Challenge')),
                ('associated_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
