# Generated by Django 3.0.7 on 2020-07-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200730_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
